%%%-------------------------------------------------------------------
%%% @author stephb
%%% @copyright (C) 2020, Arilia Wireless Inc.
%%% @doc
%%%
%%% @end
%%% Created : 31. Oct 2020 12:18 p.m.
%%%-------------------------------------------------------------------
-module(server_info).
-author("stephb").

-include("../include/inventory.hrl").

-compile([{parse_transform, rec2json}]).

%%
%%  Place holder for all functions generated by rec2json for record processor in/out
%%

%% API
-export([]).
