%%%-------------------------------------------------------------------
%%% @author stephb
%%% @copyright (C) 2020, Arilia Wireless Inc.
%%% @doc
%%%
%%% @end
%%% Created : 10. Dec 2020 11:28 a.m.
%%%-------------------------------------------------------------------
-module(stat_os_report).
-author("stephb").

-include("../include/statistics.hrl").

-compile([{parse_transform, rec2json}]).

%%
%%  Place holder for all functions generated by rec2json for record processor in/out
%%

%% API
-export([]).